In [1]:
import pandas as pd
import seaborn as sns

In [2]:
insurance_data =  pd.read_csv("insurance.csv")
insurance_data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [3]:
# cleaning,hot encoding
x=insurance_data.drop(columns=["charges"])
y=insurance_data["charges"]
x=pd.get_dummies(x,columns=["region"],drop_first=True,dtype=int)
x["sex"] = x["sex"].map({"female":1,"male":0})
x["smoker"] = x["smoker"].map({"yes":1,"no":0})
x

,age,sex,bmi,children,smoker,region_northwest,region_southeast,region_southwest
0,19,1,27.900,0,1,0,0,1
1,18,0,33.770,1,0,0,1,0
2,28,0,33.000,3,0,0,1,0
3,33,0,22.705,0,0,1,0,0
4,32,0,28.880,0,0,1,0,0
...,...,...,...,...,...,...,...,...
1333,50,0,30.970,3,0,1,0,0
1334,18,1,31.920,0,0,0,0,0
1335,18,1,36.850,0,0,0,1,0
1336,21,1,25.800,0,0,0,0,1
1337,61,1,29.070,0,1,1,0,0

In [4]:
# intreaction features 
x["age_smoker"]=x["age"]*x["smoker"]
x["bmi_smoker"]=x["bmi"]*x["smoker"]

In [11]:
# train_test_split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
# model
# train
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)
# test
# x_T=pd.DataFrame(x_test)
y_pred=model.predict(x_test)
df=pd.DataFrame(y_pred)
df.head(7)

              0
0  11244.922530
1   7419.096130
2  33108.562633
3  10825.703500
4  28165.831204
5   6492.300552
6   2795.334326

In [13]:
y_test.head(7)

764      9095.06825
887      5272.17580
890     29330.98315
1293     9301.89355
259     33750.29180
1312     4536.25900
899      2117.33885
Name: charges, dtype: float64

In [7]:
# evaluation
from sklearn.metrics import r2_score
r2 = r2_score(y_pred,y_test)
r2

0.8508509822647875