In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [2]:
titanic_df = sns.load_dataset("titanic")
titanic_df.isnull().sum()

survived         0
pclass           0
sex              0
age             49
sibsp            0
parch            0
fare             0
embarked         1
class            0
who              0
adult_male       0
deck           205
embark_town      1
alive            0
alone            0
dtype: int64

In [3]:
titanic_df.head()
# titanic_df['age'].plot(kind='box') # checking outliers in age

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
# clean_and _handle data
features =["pclass","sex","age","fare","embarked"]
target = ["survived"]
imputer = SimpleImputer(strategy = "mean") 
titanic_df[["age"]] = imputer.fit_transform(titanic_df[["age"]])
imputer = SimpleImputer(strategy = "most_frequent") 
titanic_df[['embarked']] = imputer.fit_transform(titanic_df[['embarked']])
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255 entries, 0 to 254
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     255 non-null    int64
 1   pclass       255 non-null    int64
 2   sex          255 non-null    object
 3   age          255 non-null    float64
 4   sibsp        255 non-null    int64
 5   parch        255 non-null    int64
 6   fare         255 non-null    float64
 7   embarked     255 non-null    object
 8   class        255 non-null    category
 9   who          255 non-null    object
 10  adult_male   255 non-null    bool
 11  deck         50 non-null     category
 12  embark_town  254 non-null    object
 13  alive        255 non-null    object
 14  alone        255 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 23.5+ KB

In [5]:

# Copy data
x = titanic_df[features].copy()
y = titanic_df["survived"].copy()

# Label Encoding
le = LabelEncoder()
x["sex"] = le.fit_transform(x["sex"])
x["embarked"] = le.fit_transform(x["embarked"])

x.head()

   pclass  sex   age     fare  embarked
0       3    1  22.0   7.2500         2
1       1    0  38.0  71.2833         0
2       3    0  26.0   7.9250         2
3       1    0  35.0  53.1000         2
4       3    1  35.0   8.0500         2

In [10]:
# train test split
x_train ,x_test,y_train,y_test =train_test_split(x,y,test_size = 0.2,random_state=42)
# model
clasifier = DecisionTreeClassifier(max_depth = 4)
clasifier.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=4)

In [16]:
from sklearn.metrics import accuracy_score
y_pred = clasifier.predict(x_test)
y_train_pred = clasifier.predict(x_train)

print("Training Accuracy : ",accuracy_score(y_train,y_train_pred))
print("testing Accuracy : ",accuracy_score(y_test,y_pred))

Training Accuracy :  0.8431372549019608
testing Accuracy :  0.7843137254901961

In [18]:
from sklearn.ensemble import RandomForestClassifier 
rf = RandomForestClassifier(max_depth = 4,
                            n_estimators = 401,
                            oob_score = True
                           )
rf.fit(x_train,y_train)
y_pred = rf.predict(x_test)
print("OOB score : ",rf.oob_score_)
print("accuracy score : ",accuracy_score(y_test,y_pred))

OOB score :  0.7745098039215687
accuracy score :  0.8235294117647058